//
//  PasteBoard.swift
//  Clipboard
//
//  Created by crown on 2025/9/13.
//

import AppKit
import AVFoundation
import Foundation

final class PasteBoard {
    static let main = PasteBoard()

    private let pasteboard = NSPasteboard.general
    private let timerInterval = 1.0
    private var changeCount: Int
    private var pasteModel: PasteboardModel?
    private var audioPlayer: AVAudioPlayer?
    private var timer: Timer?

    init() {
        changeCount = pasteboard.changeCount
    }

    func startListening() {
        stopListening()

        timer = Timer.scheduledTimer(
            withTimeInterval: timerInterval,
            repeats: true,
        ) { [weak self] _ in
            Task { @MainActor in
                self?.checkForChangesInPasteboard()
            }
        }
    }

    func stopListening() {
        timer?.invalidate()
        timer = nil
    }

    private func checkForChangesInPasteboard() {
        guard pasteboard.changeCount != changeCount else {
            return
        }

        if pasteModel != nil {
            changeCount = pasteboard.changeCount
            pasteModel = nil
            return
        }

        // 检查隐私设置：忽略机密内容
        if PasteUserDefaults.ignoreSensitiveContent {
            if containsSensitiveContent() {
                changeCount = pasteboard.changeCount
                return
            }
        }

        // 检查隐私设置：忽略瞬时内容
        if PasteUserDefaults.ignoreEphemeralContent {
            if isEphemeralContent() {
                changeCount = pasteboard.changeCount
                return
            }
        }

        // 检查隐私设置：忽略特定应用
        if let sourceApp = getSourceApplication() {
            let ignoredApps = PasteUserDefaults.ignoredApps
            let shouldIgnore = ignoredApps.contains { app in
                if let bundleId = app.bundleIdentifier,
                   bundleId == sourceApp.bundleIdentifier
                {
                    return true
                }
                return app.path == sourceApp.bundleURL?.path
            }

            if shouldIgnore {
                log.debug(
                    "来自忽略应用的内容，跳过记录: \(sourceApp.localizedName ?? "Unknown")",
                )
                changeCount = pasteboard.changeCount
                return
            }
        }

        guard let item = pasteboard.pasteboardItems?.first else { return }
        let types = item.types.map(\.rawValue)
        log.debug("可用类型 \(types)")

        PasteDataStore.main.addNewItem(pasteboard)
        changeCount = pasteboard.changeCount

        DispatchQueue.main.async {
            AppDelegate.shared?.triggerStatusBarPulse()
            if PasteUserDefaults.soundEnabled {
                self.playNotificationSound()
            }
        }
    }

    private func containsSensitiveContent() -> Bool {
        let types = pasteboard.types ?? []

        let sensitiveTypes = [
            "org.nspasteboard.ConcealedType",

            "com.apple.password",
            "com.apple.securetext",

            "com.agilebits.onepassword", // 1Password
            "com.lastpass.mac", // LastPass
            "com.dashlane.dashlanephonefinal", // Dashlane
            "com.keeper.KeeperPassManager", // Keeper
            "io.enpass.Enpass", // Enpass
            "com.bitwarden.desktop", // Bitwarden
        ]

        for type in types {
            if sensitiveTypes.contains(type.rawValue) {
                log.info("检测到机密内容，跳过记录: \(type.rawValue)")
                return true
            }
        }

        return false
    }

    private func isEphemeralContent() -> Bool {
        let types = pasteboard.types ?? []

        let ephemeralTypes = [
            "org.nspasteboard.TransientType", // 瞬时内容标准标识
            "org.nspasteboard.AutoGeneratedType", // 自动生成内容
            "org.nspasteboard.RestoredType", // 恢复的内容

            "de.petermaurer.TransientPasteboardType", // TextExpander/Butler
            "com.typeit4me.clipping", // TypeIt4Me

            "com.apple.pasteboard.promised-file-content-type",
        ]

        for type in types {
            let rawType = type.rawValue

            if ephemeralTypes.contains(rawType) {
                log.info("检测到瞬时内容，跳过记录: \(rawType)")
                return true
            }
        }

        return false
    }

    private func getSourceApplication() -> NSRunningApplication? {
        NSWorkspace.shared.frontmostApplication
    }

    private func playNotificationSound() {
        guard
            let url = Bundle.main.url(
                forResource: "copy",
                withExtension: "mp3",
            )
        else {
            return
        }

        do {
            let player = try AVAudioPlayer(contentsOf: url)
            player.prepareToPlay()
            player.play()
            audioPlayer = player
        } catch {
            log.warn("播放音效失败: \(error.localizedDescription)")
        }
    }

    func pasteData(_ data: PasteboardModel, _ isAttribute: Bool = true) {
        data.updateDate()
        pasteModel = data
        if let itemId = data.id {
            PasteDataStore.main.updateDbItem(id: itemId, item: data)
        }
        PasteDataStore.main.moveItemToFirst(data)
        NSPasteboard.general.clearContents()

        let shouldPasteAsPlainText = !isAttribute || PasteUserDefaults.pasteOnlyText

        if (data.type == .string) || (data.type == .rich), shouldPasteAsPlainText {
            var textToPaste = data.searchText
            if PasteUserDefaults.removeTailingNewline {
                while textToPaste.hasSuffix("\n") || textToPaste.hasSuffix("\r") {
                    textToPaste.removeLast()
                }
            }
            NSPasteboard.general.setString(textToPaste, forType: .string)
        } else if data.type == .file {
            if let filePaths = String(data: data.data, encoding: .utf8) {
                let paths = filePaths.components(separatedBy: "\n")
                    .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
                    .filter { !$0.isEmpty }

                var validURLs: [URL] = []

                for path in paths {
                    let fileURL = URL(fileURLWithPath: path)
                    if FileManager.default.fileExists(atPath: path) {
                        validURLs.append(fileURL)
                    }
                }

                guard !validURLs.isEmpty else {
                    return
                }

                pasteboard.writeObjects(validURLs as [NSPasteboardWriting])
            }
        } else {
            if data.pasteboardType.isText(),
               PasteUserDefaults.removeTailingNewline
            {
                if let attributedString = NSAttributedString(
                    with: data.data,
                    type: data.pasteboardType
                ) {
                    let mutableString = NSMutableAttributedString(
                        attributedString: attributedString
                    )
                    let originalLength = mutableString.length

                    var currentLength = originalLength
                    while currentLength > 0 {
                        let lastCharRange = NSRange(
                            location: currentLength - 1,
                            length: 1
                        )
                        let lastChar = mutableString.attributedSubstring(
                            from: lastCharRange
                        ).string

                        if lastChar == "\n" || lastChar == "\r" {
                            currentLength -= 1
                        } else {
                            break
                        }
                    }

                    if currentLength < originalLength {
                        let rangeToDelete = NSRange(
                            location: currentLength,
                            length: originalLength - currentLength
                        )
                        mutableString.deleteCharacters(in: rangeToDelete)
                    }

                    if let processedData = mutableString.toData(
                        with: data.pasteboardType
                    ) {
                        NSPasteboard.general.setData(
                            processedData,
                            forType: data.pasteboardType,
                        )
                        return
                    }
                }
            }

            NSPasteboard.general.setData(
                data.data,
                forType: data.pasteboardType,
            )
        }
    }
}
